### ISSUE TITLE
toml.decoder.TomlDecodeError: Invalid inline table encountered

### ISSUE THREAD

**Issue by Love4Taylor** [yjqiang/bili2.0#104]
```
Traceback (most recent call last):
  File "/home/love4taylor/.local/lib/python3.7/site-packages/toml/decoder.py", line 607, in load_inline_object
    _, value = candidate_group.split('=', 1)
ValueError: not enough values to unpack (expected 2, got 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/love4taylor/.local/lib/python3.7/site-packages/toml/decoder.py", line 456, in loads
    multibackslash)
  File "/home/love4taylor/.local/lib/python3.7/site-packages/toml/decoder.py", line 725, in load_line
    value, vtype = self.load_value(pair[1], strictly_valid)
  File "/home/love4taylor/.local/lib/python3.7/site-packages/toml/decoder.py", line 805, in load_value
    self.load_inline_object(v, inline_object)
  File "/home/love4taylor/.local/lib/python3.7/site-packages/toml/decoder.py", line 609, in load_inline_object
    raise ValueError("Invalid inline table encountered")
ValueError: Invalid inline table encountered

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 41, in <module>
    dict_ctrl = conf_loader.read_ctrl()
  File "/home/love4taylor/scripts/bili2.0/conf_loader.py", line 93, in read_ctrl
    return var.read_ctrl()
  File "/home/love4taylor/scripts/bili2.0/conf_loader.py", line 65, in read_ctrl
    dict_ctrl = toml.load(f)
  File "/home/love4taylor/.local/lib/python3.7/site-packages/toml/decoder.py", line 134, in load
    return loads(f.read(), _dict, decoder)
  File "/home/love4taylor/.local/lib/python3.7/site-packages/toml/decoder.py", line 458, in loads
    raise TomlDecodeError(str(err), original, pos)
toml.decoder.TomlDecodeError: Invalid inline table encountered (line 42 column 1 char 1028)
```

**Comment by yjqiang** [comment]
你自己写错了toml文件了，自己参考规范https://github.com/toml-lang/toml

**Comment by Love4Taylor** [comment]
@yjqiang 这我可不背锅. 全新 clone, 直接 cp 的示例配置, 只修改了 user.toml. 没动 ctrl.toml.

**Comment by yjqiang** [comment]
写多了dict了，串了。。。
