### ISSUE TITLE
错误代码

### ISSUE THREAD

**Issue by yushengleiming** [yjqiang/bili2.0#112]
Traceback (most recent call last):
  File "run.py", line 9, in <module>
    from bili_console import Biliconsole
  File "C:\Users\Administrator\Desktop\新建文件夹 (3)\bili2.0-master1\bili_console.py", line 7, in <module>
    from tasks.utils import UtilsTask
  File "C:\Users\Administrator\Desktop\新建文件夹 (3)\bili2.0-master1\tasks\utils.py", line 5, in <module>
    from decorator import decorator
ModuleNotFoundError: No module named 'decorator'

**Comment by yjqiang** [comment]
你们每次更新都得问一句么。。。这显然就是添加了新模块啊`pip3 install decorator`
