### ISSUE TITLE
账户密码修改后继续抽奖一段时间后，再重启脚本，链接被目标服务器拒绝

### ISSUE THREAD

**Issue by azure-crab** [yjqiang/bili2.0#121]
**问题描述**
我在今天（Apr. 22 2019）下午修改b站账户密码后忘记关闭脚本，导致脚本在一段时间内尝试抽奖但服务端一直返回密码错误。我注意到这个问题后，关闭脚本，重写配置文件并重启脚本后，本错误出现。推测是脚本的行为被b站认定为bot并拒绝了链接，是否可以通过清空cookie或者重置脚本缓存之类的方法解决问题呢？

**截图或者视频或者报错文字**
```
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\urllib3\connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\urllib3\util\connection.py", line 80, in create_connection
    raise err
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\urllib3\util\connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Program Files (x86)\Python36-32\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Program Files (x86)\Python36-32\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Program Files (x86)\Python36-32\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Program Files (x86)\Python36-32\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "C:\Program Files (x86)\Python36-32\lib\http\client.py", line 964, in send
    self.connect()
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\urllib3\connection.py", line 181, in connect
    conn = self._new_conn()
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\urllib3\connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x05320F90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\urllib3\util\retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='115.159.205.242', port=19951): Max retries exceeded with url: /captcha/v1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x05320F90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\run.py", line 52, in <module>
    loop.run_until_complete(notifier.exec_func(-2, LoginTask.handle_login_status))
  File "C:\Program Files (x86)\Python36-32\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "C:\Users\****\Downloads\bili2.0-master\notifier.py", line 134, in exec_func
    result = await var.notify_all(func, *args)
  File "C:\Users\****\Downloads\bili2.0-master\notifier.py", line 27, in notify_all
    result = await user.accept(func, *args)
  File "C:\Users\****\Downloads\bili2.0-master\user.py", line 136, in accept
    return await func(self, *args)
  File "C:\Users\****\Downloads\bili2.0-master\tasks\login.py", line 11, in handle_login_status
    return await LoginTask.login(user)
  File "C:\Users\****\Downloads\bili2.0-master\tasks\login.py", line 66, in login
    captcha = LoginReq.cnn_captcha(binary_rsp)
  File "C:\Users\****\Downloads\bili2.0-master\reqs\login.py", line 67, in cnn_captcha
    response = requests.post(url, json=json)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\requests\api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='115.159.205.242', port=19951): Max retries exceeded with url: /captcha/v1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x05320F90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it',))
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x04716D30>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x04BD5490>, 94039.468)]']
connector: <aiohttp.connector.TCPConnector object at 0x04716CB0>
```

**必要的系统信息描述等**
windows 1809, python3.6.5

**最近何时更新的脚本**
昨天(Apr. 22 2019)晚

**最后确认**
- [x] 我仔细看了requirements.tx，确认里面的模块我都安装并及时更新了
- [x] 我代码上次更新时间距今没有超过 2 个月以上
- [x] 我仔细阅读了 conf 里面的 sample 文件（包括user.sample.toml和ctrl.sample.toml），并发现如果发生了改动，及时更新了我的 toml 对应文件
- [x] 我仔细检查了 readme 最近更新情况，并查看了最近更新内容

**Comment by yjqiang** [comment]
这个应该是验证码提供端暂时屏蔽了你。可以通过自己设置cookie或者等一段时间后去解决。

**Comment by azure-crab** [comment]
> 这个应该是验证码提供端（验证码是用了上游项目的服务点）暂时屏蔽了你。可以通过自己设置cookie或者等一段时间后去解决。
我尝试在chrome浏览器中确认bilibili直播页面的cookies的内容，但是其中分了非常多的条目，请问我该如何确定是哪个条目的内容呢？（抱歉，我对cookies不是特别了解……）

**Comment by azure-crab** [comment]
> 这个应该是验证码提供端（验证码是用了上游项目的服务点）暂时屏蔽了你。可以通过自己设置cookie或者等一段时间后去解决。

我尝试在chrome浏览器中确认bilibili直播页面的cookies的内容，但是其中分了非常多的条目，请问我该如何确定是哪个条目的内容呢？（抱歉，我对cookies不是特别了解……）

**Comment by azure-crab** [comment]
我通过检查chrome发的包确定了cookie，不过api还是提示没有登陆，可能不仅仅需要cookie？（id和ts用*替换了）
```
api提示没有登录
{'ts': *, 'message': 'Account is not logined.', 'code': -101}
[2019-04-23 00:51:37] token可能过期 (用户id:0 名字:*)
api提示没有登录
```

**Comment by yjqiang** [comment]
你等吧……  应该是token一类的没弄好  等着解禁或者可以手动去tasks/login切换验证码输入方式，目前用cnn，你可以改成input。

**Comment by azure-crab** [comment]
等待约10小时后问题自动解决，因此关闭此issue。

**Comment by falcomzwei** [comment]
> 等待约10小时后问题自动解决，因此关闭此issue。

试了下重启路由器，ip换了之后就直接登上了
