### ISSUE TITLE
之前改了user文件后就开始闪退，然后重装电脑系统，重装python，重装环境，依然闪退

### ISSUE THREAD

**Issue by piaopiaoa** [yjqiang/bili2.0#123]
如题，刚刚重新才下载的脚本，全部设置好之后，运行run.py，然后闪出一大堆看不清的代码之后，闪退，环境我确定全部打完，也成功打上，然后user和ctrl也创建好了，user里面添加了我自己的账号，只不过我只知道账号密码和UID其他的不知道的就空着，ctrl创建好复制之后就再也没动过，开run.py依然闪退，无果

**Comment by piaopiaoa** [comment]
用视频软件捕捉到闪退瞬间出现的文字是“由于计算机积极拒绝，无法连接”

**Comment by yjqiang** [comment]
求求你不要双击打开，用cmd好吧。

**Comment by yjqiang** [comment]
我要截图或者完整的log

**Comment by piaopiaoa** [comment]
![问题](https://user-images.githubusercontent.com/50024282/56820419-72a38d80-687e-11e9-9d81-d84ebd6e087f.PNG)
闪退前的信息是这个

**Comment by yjqiang** [comment]
建议截全了，从头到尾。另外我觉得可能是https://github.com/yjqiang/bili2.0/issues/121 一样的原因。

**Comment by piaopiaoa** [comment]
我看了一下121，情况确实是一样的，我试试更改ip

**Comment by piaopiaoa** [comment]
完整：
Traceback (most recent call last):
  File "C:\Users\windows\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3-1.24.2-py3.6.egg\urllib3\connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "C:\Users\windows\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3-1.24.2-py3.6.egg\urllib3\util\connection.py", line 80, in create_connection
    raise err
  File "C:\Users\windows\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3-1.24.2-py3.6.egg\urllib3\util\connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\windows\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3-1.24.2-py3.6.egg\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Users\windows\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3-1.24.2-py3.6.egg\urllib3\connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\windows\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\windows\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\windows\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\windows\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "C:\Users\windows\AppData\Local\Programs\Python\Python36-32\lib\http\client.py", line 964, in send
    self.connect()
  File "C:\Users\windows\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3-1.24.2-py3.6.egg\urllib3\connection.py", line 181, in connect
    conn = self._new_conn()
  File "C:\Users\windows\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3-1.24.2-py3.6.egg\urllib3\connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x045797D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\windows\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests-2.21.0-py3.6.egg\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\windows\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3-1.24.2-py3.6.egg\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\windows\AppData\Local\Programs\Python\Python36-32\lib\site-packages\urllib3-1.24.2-py3.6.egg\urllib3\util\retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='115.159.205.242', port=19951): Max retries exceeded with url: /captcha/v1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x045797D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\windows\Desktop\bili2.0-master\run.py", line 49, in <module>
    loop.run_until_complete(notifier.exec_func(-2, LoginTask.handle_login_status))
  File "C:\Users\windows\AppData\Local\Programs\Python\Python36-32\lib\asyncio\base_events.py", line 468, in run_until_complete
    return future.result()
  File "C:\Users\windows\Desktop\bili2.0-master\notifier.py", line 134, in exec_func
    result = await var.notify_all(func, *args)
  File "C:\Users\windows\Desktop\bili2.0-master\notifier.py", line 27, in notify_all
    result = await user.accept(func, *args)
  File "C:\Users\windows\Desktop\bili2.0-master\user.py", line 136, in accept
    return await func(self, *args)
  File "C:\Users\windows\Desktop\bili2.0-master\tasks\login.py", line 11, in handle_login_status
    return await LoginTask.login(user)
  File "C:\Users\windows\Desktop\bili2.0-master\tasks\login.py", line 66, in login
    captcha = LoginReq.cnn_captcha(binary_rsp)
  File "C:\Users\windows\Desktop\bili2.0-master\reqs\login.py", line 70, in cnn_captcha
    response = requests.post(url, json=json)
  File "C:\Users\windows\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests-2.21.0-py3.6.egg\requests\api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\windows\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests-2.21.0-py3.6.egg\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\windows\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests-2.21.0-py3.6.egg\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\windows\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests-2.21.0-py3.6.egg\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\windows\AppData\Local\Programs\Python\Python36-32\lib\site-packages\requests-2.21.0-py3.6.egg\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='115.159.205.242', port=19951): Max retries exceeded with url: /captcha/v1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x045797D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x03B8EEB0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x040627A0>, 5227.078)]']
connector: <aiohttp.connector.TCPConnector object at 0x03B8EF30>

**Comment by yjqiang** [comment]
确定了就是 #121

**Comment by piaopiaoa** [comment]
我也是在脚本未关闭情况下出现的问题，系统版本1809 企业版，python 3.6.5.更改IP后无果，还是闪退

**Comment by yjqiang** [comment]
只要还是这个报错信息，肯定就是验证码服务器问题，与脚本无关。

**Comment by piaopiaoa** [comment]
那解决方式是什么呢？

**Comment by yjqiang** [comment]
#121已经说了啊，等或者改cnn那里
