### ISSUE TITLE
ctrl.toml解析报错

### ISSUE THREAD

**Issue by a253208088** [yjqiang/bili2.0#126]
**再确认一次 issue 题目**
请记得把 issue 标题改成问题描述的概述，而不是简单的一句话，《电脑开不了了》、《闪退了》、《救命啊》这些

**问题描述**
尽量详细叙述发生时间等

**截图或者视频或者报错文字**
截图请务必把名字等信息打码

**必要的系统信息描述等**
python 版本以及系统版本信息

**最近何时更新的脚本**
几天前还是几小时前

**最后确认**
- [ok ] 我仔细看了requirements.tx，确认里面的模块我都安装并及时更新了
- [ok ] 我代码上次更新时间距今没有超过 2 个月以上
- [ ok] 我仔细阅读了 conf 里面的 sample 文件（包括user.sample.toml和ctrl.sample.toml），并发现如果发生了改动，及时更新了我的 toml 对应文件
- [ ok] 我仔细检查了 readme 最近更新情况，并查看了最近更新内容
Traceback (most recent call last):
  File "run.py", line 45, in <module>
    dict_ctrl = conf_loader.read_ctrl()
  File "E:\bili2.0-master\conf_loader.py", line 91, in read_ctrl
    return var.read_ctrl()
  File "E:\bili2.0-master\conf_loader.py", line 67, in read_ctrl
    dict_ctrl = toml.load(f)
  File "C:\Users\25320\AppData\Local\Programs\Python\Python36\lib\site-packages\toml.py", line 108, in load
    return loads(f.read(), _dict)
  File "C:\Users\25320\AppData\Local\Programs\Python\Python36\lib\site-packages\toml.py", line 373, in loads
    multibackslash)
  File "C:\Users\25320\AppData\Local\Programs\Python\Python36\lib\site-packages\toml.py", line 478, in _load_line
    value, vtype = _load_value(pair[1], _dict, strictly_valid)
  File "C:\Users\25320\AppData\Local\Programs\Python\Python36\lib\site-packages\toml.py", line 635, in _load_value
    return (_load_array(v, _dict), "array")
  File "C:\Users\25320\AppData\Local\Programs\Python\Python36\lib\site-packages\toml.py", line 739, in _load_array
    nval, ntype = _load_value(a[i], _dict)
  File "C:\Users\25320\AppData\Local\Programs\Python\Python36\lib\site-packages\toml.py", line 635, in _load_value
    return (_load_array(v, _dict), "array")
  File "C:\Users\25320\AppData\Local\Programs\Python\Python36\lib\site-packages\toml.py", line 739, in _load_array
    nval, ntype = _load_value(a[i], _dict)
  File "C:\Users\25320\AppData\Local\Programs\Python\Python36\lib\site-packages\toml.py", line 664, in _load_value
    v = int(v)
ValueError: invalid literal for int() with base 10: '02:00:00'

**Comment by yjqiang** [comment]
你截图ctrl.toml休眠时间设置部分

**Comment by a253208088** [comment]
控制台查询统计数据也报错

Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\25320\AppData\Local\Programs\Python\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\25320\AppData\Local\Programs\Python\Python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\25320\AppData\Local\Programs\Python\Python36\lib\cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "C:\Users\25320\AppData\Local\Programs\Python\Python36\lib\cmd.py", line 217, in onecmd
    return func(arg)
  File "E:\bili2.0-master\bili_console.py", line 130, in do_1
    user_id, = self.parse(arg, '-u:')
  File "E:\bili2.0-master\bili_console.py", line 103, in parse
    int_value = convert2int(opt_value)
  File "E:\bili2.0-master\bili_console.py", line 43, in convert2int
    return int(orig)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by a253208088** [comment]
![TIM截图20190504204511](https://user-images.githubusercontent.com/29302427/57179186-8fa71480-6ead-11e9-8b05-7e506c846b8f.png)

**Comment by yjqiang** [comment]
你是用了半角符号么

**Comment by a253208088** [comment]
我从举例复制下来的

**Comment by a253208088** [comment]
只改了数字,去了空格

**Comment by yjqiang** [comment]
控制台你更新代码即可，我修复了

**Comment by yjqiang** [comment]
休眠设置没问题，你把整个ctrl文件弄上来吧

**Comment by a253208088** [comment]
[ctrl.zip](https://github.com/yjqiang/bili2.0/files/3144384/ctrl.zip)

**Comment by yjqiang** [comment]
本地测试toml正常读写，你看看toml模块是不是没更新

**Comment by a253208088** [comment]
更新了的,还是那样

**Comment by yjqiang** [comment]
你试试
[ctrl.zip](https://github.com/yjqiang/bili2.0/files/3144395/ctrl.zip)

**Comment by a253208088** [comment]
还是一样报错

**Comment by yjqiang** [comment]
[测试.zip](https://github.com/yjqiang/bili2.0/files/3144399/default.zip)
n你运行一下测试文件，看看报错么

**Comment by a253208088** [comment]
报一样的错

**Comment by yjqiang** [comment]
你自己环境出问题了，查看toml模块是否最新，`print(toml.__version__)`

**Comment by a253208088** [comment]
E:\>print(toml.__version__)
无法初始化设备 PRN

**Comment by yjqiang** [comment]
> E:>print(toml.**version**)
> 无法初始化设备 PRN

？？？
先进入python啊。。。
写一个python文件
```python
import toml
print(toml.__version__)
```

**Comment by a253208088** [comment]
>>> print(toml.__version__)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'toml' is not defined

**Comment by a253208088** [comment]
>>> import toml
>>> print(toml.__version__)
0.9.4
>>>

**Comment by a253208088** [comment]
抱歉是小白

**Comment by yjqiang** [comment]
https://github.com/yjqiang/bili2.0/issues/126#issuecomment-489325040

0.9.4是个锤子的最新版

**Comment by a253208088** [comment]
pip没更新   抱歉

**Comment by a253208088** [comment]
更新弄好了,原来我一直以为使用方法里的pip install -r requirements.txt会更新,,,,,
但是控制台还是没法用 ,是最新代码,,可以输出控制台说明,但不管用那个功能报错
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\25320\AppData\Local\Programs\Python\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\25320\AppData\Local\Programs\Python\Python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\25320\AppData\Local\Programs\Python\Python36\lib\cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "C:\Users\25320\AppData\Local\Programs\Python\Python36\lib\cmd.py", line 217, in onecmd
    return func(arg)
  File "E:\bili2.0-master\bili_console.py", line 130, in do_1
    user_id, = self.parse(arg, '-u:')
  File "E:\bili2.0-master\bili_console.py", line 103, in parse
    int_value = convert2int(opt_value)
  File "E:\bili2.0-master\bili_console.py", line 43, in convert2int
    return int(orig)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by yjqiang** [comment]
fixed

**Comment by a253208088** [comment]
萌新谢谢大佬的帮助
