### ISSUE TITLE
在运行pip install -r requirements.txt 安装模块时出现错误

### ISSUE THREAD

**Issue by yushengleiming** [yjqiang/bili2.0#128]
ERROR: Exception:
Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\pip\_internal\cli\base_command.py", line 178, in main
    status = self.run(options, args)
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\pip\_internal\commands\install.py", line 326, in run
    self.name, wheel_cache
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\pip\_internal\cli\base_command.py", line 288, in populate_requirement_set
    use_pep517=options.use_pep517):
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\pip\_internal\req\req_file.py", line 103, in parse_requirements
    filename, comes_from=comes_from, session=session
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\pip\_internal\download.py", line 481, in get_file_content
    content = auto_decode(f.read())
  File "c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages\pip\_internal\utils\encoding.py", line 38, in auto_decode
    locale.getpreferredencoding(False) or sys.getdefaultencoding(),
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 49: illegal multibyte sequence

**Comment by yjqiang** [comment]
这个应该不是我的问题吧？

**Comment by yushengleiming** [comment]
> 这个应该不是我的问题吧？

emmm我也不知道是什么问题

**Comment by yjqiang** [comment]
你试试`pip3 install -r requirements.tx`

**Comment by yushengleiming** [comment]
还是一样的

**Comment by yushengleiming** [comment]
C:\Users\Administrator\Desktop\bili2.0-master>pip show pip
Name: pip
Version: 19.1
Summary: The PyPA recommended tool for installing Python packages.
Home-page: https://pip.pypa.io/
Author: The pip developers
Author-email: pypa-dev@groups.google.com
License: MIT
Location: c:\users\administrator\appdata\local\programs\python\python36\lib\site-packages
Requires:
Required-by: 
 我的pip版本

**Comment by yjqiang** [comment]
你手动挨个安装
例如`pip install toml` `pip install aiojobs`

**Comment by yjqiang** [comment]
https://github.com/google/tangent/issues/11#issuecomment-455910041
看上去这个可以

**Comment by yushengleiming** [comment]
可以了 谢谢大佬

**Comment by yjqiang** [comment]
> 可以了 谢谢大佬

是用了https://github.com/yjqiang/bili2.0/issues/128#issuecomment-489607309这个办法么？

**Comment by yushengleiming** [comment]
是的

**Comment by yushengleiming** [comment]
对了。用了这个方法后系统中某些软件会乱码但现象好像不普遍，关闭后脚本依然可以运行，乱码也恢复了。

**Comment by yjqiang** [comment]
en 这只是为了安装  安装完成可以关了

**Comment by yushengleiming** [comment]
> en 这只是为了安装 安装完成可以关了

emm  我觉是这个意思  如果有人用了这个方法后 然后发现各种软件乱码什么的说不定会一遍遍重装软件呢 233

**Comment by yushengleiming** [comment]
> en 这只是为了安装 安装完成可以关了

emm 我就是这个意思 如果有人用了这个方法后 然后发现各种软件乱码什么的说不定会一遍遍重装软件呢 233

**Comment by pjy612** [comment]
在txt顶部加上。
#coding=utf-8
或者
把txt的编码改成ANSI 就可以正常装模块了。

**Comment by yjqiang** [comment]
pip 这里解析应该还是gbk在Windows下面，中文就成了utf8，然后gg，https://github.com/yjqiang/bili2.0/commit/2743ae8ee8e0e6f27d16ff3a80085821281064ad
