### ISSUE TITLE
请问大佬这是在哪出现问题的“aiojobs”

### ISSUE THREAD

**Issue by Jutean** [yjqiang/bili2.0#133]
Traceback (most recent call last):
  File "run.py", line 9, in <module>
    import notifier
  File "C:\Users\Administrator\Desktop\bili2.0-master\notifier.py", line 5, in <module>
    import aiojobs
ModuleNotFoundError: No module named 'aiojobs'

**Comment by Jutean** [comment]
python -m pip install --upgrade pip在用这个试试

**Comment by Jutean** [comment]
Traceback (most recent call last):
  File "run.py", line 9, in <module>
    import notifier
  File "C:\Users\Administrator\Desktop\bili2.0-master\notifier.py", line 5, in <module>
    import aiojobs
ModuleNotFoundError: No module named 'aiojobs'

更新完还是一样

**Comment by Jutean** [comment]
pip3 install decorator这个也装了

**Comment by yjqiang** [comment]
pip3 install aiojobs

**Comment by Jutean** [comment]
pip3了一大堆才搞定

**Comment by Jutean** [comment]
谢谢大佬提供思路

**Comment by yjqiang** [comment]
缺少模块aiojobs啊  requirements.txt里面写着  怎么安装模块你自己查吧
