### ISSUE TITLE
大佬新增加用户报错

### ISSUE THREAD

**Issue by Jutean** [yjqiang/bili2.0#134]
File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1016, in _send_output
    self.send(msg)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 956, in send
    self.connect()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connection.py", line 181, in connect
    conn = self._new_conn()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000002ABDB84AAC8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\urllib3\util\retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='115.159.205.242', port=19951): Max retries exceeded with url: /captcha/v1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002ABDB84AAC8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 85, in <module>
    loop.run_until_complete(notifier.exec_task(LoginTask))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 584, in run_until_complete
    return future.result()
  File "C:\Program Files (x86)\bili2.0-master\notifier.py", line 164, in exec_task
    return await var_notifier.exec_task(task, *args, **kwargs)
  File "C:\Program Files (x86)\bili2.0-master\notifier.py", line 144, in exec_task
    return await self.exec_forced_task(task, *args, **kwargs)
  File "C:\Program Files (x86)\bili2.0-master\notifier.py", line 134, in exec_forced_task
    user, task.work, *args)
  File "C:\Program Files (x86)\bili2.0-master\notifier.py", line 111, in run_forced_func
    return await user.exec_func(func, *args, **kwargs)
  File "C:\Program Files (x86)\bili2.0-master\user.py", line 136, in exec_func
    return await func(self, *args, **kwargs)
  File "<C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\decorator.py:decorator-gen-3>", line 2, in work
  File "C:\Program Files (x86)\bili2.0-master\tasks\task_func_decorator.py", line 35, in normal
    return await func(user, *args, **kwargs)
  File "C:\Program Files (x86)\bili2.0-master\tasks\login.py", line 18, in work
    await LoginTask.handle_login_status(user)
  File "C:\Program Files (x86)\bili2.0-master\tasks\login.py", line 23, in handle_login_status
    return await LoginTask.login(user)
  File "C:\Program Files (x86)\bili2.0-master\tasks\login.py", line 78, in login
    captcha = LoginReq.cnn_captcha(binary_rsp)
  File "C:\Program Files (x86)\bili2.0-master\reqs\login.py", line 70, in cnn_captcha
    response = requests.post(url, json=json)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='115.159.205.242', port=19951): Max retries exceeded with url: /captcha/v1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000002ABDB84AAC8>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000002ABDB5F2208>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000002ABDB7318E8>, 1240650.39)]']
connector: <aiohttp.connector.TCPConnector object at 0x000002ABDB5F29E8>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000002ABDB6FEC88>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000002ABDB731A68>, 1240650.5)]']
connector: <aiohttp.connector.TCPConnector object at 0x000002ABDB5EAD68>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000002ABDB747908>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x000002ABDB747CC0>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000002ABDB731948>, 1240650.625)]']
connector: <aiohttp.connector.TCPConnector object at 0x000002ABDB747E80>
Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x000002ABDB731BE8>, 1240650.875)]']
connector: <aiohttp.connector.TCPConnector object at 0x000002ABDB7689B0>

**Comment by yjqiang** [comment]
验证码服务器拒绝服务

**Comment by Jutean** [comment]
这该如何解决鸭？

**Comment by someash** [comment]
换一个ip登录或者等几个小时。。。

**Comment by Jutean** [comment]
好的，谢谢大佬们
