### ISSUE TITLE
 在一个非套接字上尝试了一个操作

### ISSUE THREAD

**Issue by Jutean** [yjqiang/bili2.0#135]
Traceback (most recent call last):
  File "C:\Program Files (x86)\bili2.0-master\run.py", line 153, in <module>
    loop.run_until_complete(asyncio.wait(tasks+other_tasks))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line
571, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line
539, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line
1739, in _run_once
    event_list = self._selector.select(timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\selectors.py", line 323, in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\selectors.py", line 314, in _select
    r, w, x = select.select(r, w, w, timeout)
OSError: [WinError 10038] 在一个非套接字上尝试了一个操作。

**Comment by Jutean** [comment]
之前的版本一个月出现一次，现在的版本每天出现一次，这是咋回事？求大佬解答
环境：win数据中心2016

**Comment by yjqiang** [comment]
duplicated #85

**Comment by Jutean** [comment]
这该咋整呀，大佬

**Comment by yjqiang** [comment]
py bug

**Comment by pjy612** [comment]
弄个自启吧。
run.py
```python
#顶部加上
import os

#底部改成
try:
    if other_tasks:
        loop.run_until_complete(asyncio.wait(tasks+other_tasks))
    loop.run_forever()
    if console_thread is not None:
        console_thread.join()
except:
    os._exit(0)
```
looprun.bat
```cmd
@echo off
:loop
python run.py
goto loop
pause
```
然后用looprun.bat 启动。
出了错就把自己干掉然后重启 = =。笨办法。
