### ISSUE TITLE
_sqlite3出错，及希望明确运行版本

### ISSUE THREAD

**Issue by StarryFK** [yjqiang/bili2.0#136]
先感谢一下作者大大的无私付出，然后希望能明确给出一下应该使用的Python版本，我用了好几个Python3.6+的版本都会爆代码上的错误，用不同的版本错误还都是不一样的，先是用的Python3.6.0，不行，然后用的3.7.3，不行，再用的3.6.8，还是不行，下面是我用3.7.3时显示的错误：

```
Traceback (most recent call last):
  File "run.py", line 36, in <module>                                                  from substance.monitor_substance_raffle import SubstanceRaffleMonitor
  File "/root/python/bili2.0/substance/monitor_substance_raffle.py", line 14, in <module>
    from tasks.substance_raffle_handler import (
  File "/root/python/bili2.0/tasks/substance_raffle_handler.py", line 5, in <module>
    from substance import substance_raffle_sql
  File "/root/python/bili2.0/substance/substance_raffle_sql.py", line 1, in <module>
    import sqlite3  # sqlite是个很灵活的东西，会自动转换，但是如果错误type且无法转 换那么也不报错,传说中的沙雕feature https://www.sqlite.org/faq.html#q3
  File "/usr/local/lib/python3.6/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.6/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'
```

**Comment by yjqiang** [comment]
https://bugs.python.org/issue32120 python 3.6.1之后应该就没问题了。

**Comment by yjqiang** [comment]
https://github.com/pyenv/pyenv/issues/108#issuecomment-359161050
https://github.com/pyenv/pyenv/issues/108#issuecomment-33567456
这两个或许可以解决

**Comment by StarryFK** [comment]
解决了，大概是编译python时的环境的问题，debian下安装了libsqlite3-dev之后再进行编译python，然后运行程序就没有问题了，感谢

**Comment by yjqiang** [comment]
> 解决了，大概是编译python时的环境的问题，debian下安装了libsqlite3-dev之后再进行编译python，然后运行程序就没有问题了，感谢

你干嘛自己编译啊。。坑多得一b

**Comment by someash** [comment]
我也是debian环境。。。pyenv不是很好用的么。。。。用这个装python
