### ISSUE TITLE
运行run.py出错

### ISSUE THREAD

**Issue by Skytraces** [yjqiang/bili2.0#138]
requirements已经安装好了，但是运行run.py的时候还是闪退，cmd的报告是这样的，求教大佬哪里出了问题
Traceback (most recent call last):
  File "F:\tools\bilibili\live master\bili2.0-master\run.py", line 9, in <module>
    import notifier
  File "F:\tools\bilibili\live master\bili2.0-master\notifier.py", line 7, in <module>
    import bili_statistics
  File "F:\tools\bilibili\live master\bili2.0-master\bili_statistics.py", line 42, in <module>
    @attr.s(slots=True)
  File "F:\tools\bilibili\live master\bili2.0-master\bili_statistics.py", line 52, in DuplicateChecker
    validator=attr.validators.deep_iterable(
AttributeError: module 'attr.validators' has no attribute 'deep_iterable'

**Comment by yjqiang** [comment]
自己在本issue内搜索该问题
