### ISSUE TITLE
......怎么整

### ISSUE THREAD

**Issue by heatded** [yjqiang/bili2.0#143]
>>>python D:\pvz\bili2.0-master\run.py
Traceback (most recent call last):
  File "D:\pvz\bili2.0-master\run.py", line 44, in <module>
    dict_user = conf_loader.read_user()
  File "D:\pvz\bili2.0-master\conf_loader.py", line 93, in read_user
    return var.read_user()
  File "D:\pvz\bili2.0-master\conf_loader.py", line 68, in read_user
    return self.toml_load(self.file_user)
  File "D:\pvz\bili2.0-master\conf_loader.py", line 40, in toml_load
    return toml.load(f)
  File "D:\python\lib\site-packages\toml\decoder.py", line 134, in load
    return loads(f.read(), _dict, decoder)
  File "D:\python\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 23: invalid continuation byte
CSDN上说把"r"换"rd",也不知道怎么搞

**Comment by yjqiang** [comment]
代码没有问题  你不要用记事本自己编辑toml文件  用vscode这些

**Comment by heatded** [comment]
> 代码没有问题 你不要用记事本自己编辑toml文件 用vscode这些

我用的word 我看里面有对应语言......下个vscoda试试
