### ISSUE TITLE
ValueError: This float doesn't have a leading digit

### ISSUE THREAD

**Issue by 526462712** [yjqiang/bili2.0#149]
**再确认一次 issue 题目**
请记得把 issue 标题改成问题描述的概述，而不是简单的一句话，《电脑开不了了》、《闪退了》、《救命啊》这些

**问题描述**
尽量详细叙述发生时间等

**截图或者视频或者报错文字**
截图请务必把名字等信息打码

**必要的系统信息描述等**
python 版本以及系统版本信息

**最近何时更新的脚本**
几天前还是几小时前

**最后确认**
- [x] 我仔细看了requirements.tx，确认里面的模块我都安装并及时更新了
- [x] 我代码上次更新时间距今没有超过 2 个月以上
- [x] 我仔细阅读了 conf 里面的 sample 文件（包括user.sample.toml和ctrl.sample.toml），并发现如果发生了改动，及时更新了我的 toml 对应文件
- [x] 我仔细检查了 readme 最近更新情况，并查看了最近更新内容

**Comment by yjqiang** [comment]
你连截图都没有？

**Comment by 526462712** [comment]
[root@vultr bili2]# python3 run.py
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/site-packages/toml/decoder.py", line 456, in loads
    multibackslash)
  File "/usr/local/python3/lib/python3.6/site-packages/toml/decoder.py", line 725, in load_line
    value, vtype = self.load_value(pair[1], strictly_valid)
  File "/usr/local/python3/lib/python3.6/site-packages/toml/decoder.py", line 832, in load_value
    raise ValueError("This float doesn't have a leading "
ValueError: This float doesn't have a leading digit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 48, in <module>
    dict_task = conf_loader.read_task()
  File "/root/renkun/bili2/conf_loader.py", line 101, in read_task
    return var.read_task()
  File "/root/renkun/bili2/conf_loader.py", line 74, in read_task
    return self.toml_load(self.file_task)
  File "/root/renkun/bili2/conf_loader.py", line 40, in toml_load
    return toml.load(f)
  File "/usr/local/python3/lib/python3.6/site-packages/toml/decoder.py", line 134, in load
    return loads(f.read(), _dict, decoder)
  File "/usr/local/python3/lib/python3.6/site-packages/toml/decoder.py", line 458, in loads
    raise TomlDecodeError(str(err), original, pos)
toml.decoder.TomlDecodeError: This float doesn't have a leading digit (line 48 column 1 char 1979)

requirement.txt已更新，上一个正常使用的版本是4月初的版本

**Comment by yjqiang** [comment]
你更新了task.toml改错了，自己检查，如果检查不出来，上传zip文件
