### ISSUE TITLE
获得辣条的返回信息最近出现错误

### ISSUE THREAD

**Issue by j6189802** [yjqiang/bili2.0#157]
Task exception was never retrieved
future: <Task finished coro=<run_forced_func() done, defined at D:\bili2.0-master\bili2.0-master\notifier.py:109> exception=AttributeError("'NoneType' object has no attribute 'group'",)>
Traceback (most recent call last):
  File "D:\bili2.0-master\bili2.0-master\notifier.py", line 111, in run_forced_func
    return await user.exec_func(func, *args, **kwargs)
  File "D:\bili2.0-master\bili2.0-master\user.py", line 123, in exec_func
    return await func(self, *args, **kwargs)
  File "<C:\Users\Samsung\AppData\Local\Programs\Python\Python36\lib\site-packages\decorator.py:decorator-gen-39>", line 2, in work
  File "D:\bili2.0-master\bili2.0-master\tasks\task_func_decorator.py", line 35, in normal
    return await func(user, *args, **kwargs)
  File "D:\bili2.0-master\bili2.0-master\tasks\guard_raffle_handler.py", line 52, in work
    bili_statistics.add2results(result.group(2), user.id, result.group(4))
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by yjqiang** [comment]
更新代码  早就修复了
