### ISSUE TITLE
最新的代码，一运行出现以下提示

### ISSUE THREAD

**Issue by zhz1237ok** [yjqiang/bili2.0#158]
Traceback (most recent call last):
  File "run.py", line 48, in <module>
    dict_task = conf_loader.read_task()
  File "/root/bili2.0-master/conf_loader.py", line 101, in read_task
    return var.read_task()
  File "/root/bili2.0-master/conf_loader.py", line 74, in read_task
    return self.toml_load(self.file_task)
  File "/root/bili2.0-master/conf_loader.py", line 40, in toml_load
    return toml.load(f)
  File "/usr/local/lib/python3.7/site-packages/toml/decoder.py", line 134, in load
    return loads(f.read(), _dict, decoder)
  File "/usr/local/lib/python3.7/site-packages/toml/decoder.py", line 227, in loads
    original, i)
toml.decoder.TomlDecodeError: Found invalid character in key name: '{'. Try quoting the key name. (line 9 column 13 char 624)

**Comment by yjqiang** [comment]
task.toml文件你自己改错了

**Comment by zhz1237ok** [comment]
其中有一行看不懂

# sub-table({'custom_task_arrangement': {'user0': {}, 'user1': {}}})，name与user.toml内的相同

[custom_task_arrangement."805023197@qq.com"] 这样改算对吗，那如果不是邮箱的话不加双引号对吗

**Comment by yjqiang** [comment]
不是邮箱可以不加
