### ISSUE TITLE
奇怪的403频繁导致取消全部任务

### ISSUE THREAD

**Issue by someash** [yjqiang/bili2.0#162]
并没有进入休眠时间
多次刷下面这个东西，然后取消所有任务

[2019-07-03 00:21:59] 403频繁, https://api.live.bilibili.com/lottery/v1/Storm/join?access_key=933ef67cff08c33b804b5f28778e0671&actionKey=appkey&appkey=1d8b6e7d45233436&build=520001&device=android&id=1238692192038&mobi_app=android&platform=android&ts=1562084519&sign=63ef134a88b517dc84806b22e344d285, {'headers': {'User-Agent': 'bili-universal/6570 CFNetwork/894 Darwin/17.4.0', 'Accept-encoding': 'gzip', 'Buvid': '000ce0b9b9b4e342ad4f421bcae5e0ce', 'Display-ID': '146771405-1521008435', 'Accept-Language': 'zh-CN', 'Accept': 'text/html,application/xhtml+xml,*/*;q=0.8', 'Connection': 'keep-alive', 'cookie': 'bili_jct=27e4cf497aa4360b955c802042a5c568;DedeUserID=332121422;DedeUserID__ckMd5=85f1c4c1b27e5873;sid=immjawi2;SESSDATA=229a23b0%2C1564676469%2Cbd284a71'}}
SSL error in data received
protocol: <asyncio.sslproto.SSLProtocol object at 0x000001F8CB2B10B8>
transport: <_SelectorSocketTransport fd=1180 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "C:\Users\11034\Anaconda3\lib\asyncio\sslproto.py", line 526, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "C:\Users\11034\Anaconda3\lib\asyncio\sslproto.py", line 207, in feed_ssldata
    self._sslobj.unwrap()
  File "C:\Users\11034\Anaconda3\lib\ssl.py", line 767, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL: KRB5_S_INIT] application data after close notify (_ssl.c:2609)

版本：python 3.7 （anaconda）

最近一次更新

**Comment by yjqiang** [comment]
https://github.com/aio-libs/aiohttp/issues/3535#issuecomment-497469002

**Comment by someash** [comment]
所以要等3.7.4?

**Comment by yjqiang** [comment]
> 所以要等3.7.4?

或者  3.7.4 或者 3.8。不要着急，https://github.com/yjqiang/bili2.0/issues/85 ，这货 3.7 分支根本没有修复，必须等 3.8

**Comment by pjy612** [comment]
ssl？ 大佬 API 从 https 换成 http 是否可行？

**Comment by yjqiang** [comment]
> ssl？ 大佬 API 从 https 换成 http 是否可行？

可行但不建议  cookie不加密那就是光屁股走路了

**Comment by yjqiang** [comment]
https://pythoninsider.blogspot.com/2019/07/python-374-is-now-available.html
