### ISSUE TITLE
Ubuntu下Docker启动报错Job processing failed

### ISSUE THREAD

**Issue by PhoeniXuzoo** [yjqiang/bili2.0#169]
系统环境：Ubuntu 18.04.2 LTS
问题描述：使用Readme.md文件中Docker in Linux的命令后，提示Job processing failed。具体信息如下：
Job processing failed
job: <Job coro=<<coroutine object User.exec_func at 0x7f42c7b29048>>>
Traceback (most recent call last):
  File "/app/user.py", line 120, in exec_func
    return await func(self, *args, **kwargs)
  File "</usr/local/lib/python3.6/site-packages/decorator.py:decorator-gen-30>", line 2, in work
  File "/app/tasks/task_func_decorator.py", line 20, in unique
    result = await func(user, *args, **kwargs)
  File "/app/tasks/live_daily_job.py", line 287, in work
    await SendGiftTask.send_medal_gift(user, gift_intimacy)
  File "/app/tasks/live_daily_job.py", line 239, in send_medal_gift
    send2medal_by_uid = user.task_ctrl['send2medal_by_uid']

多次尝试后发现，此报错信息是在终端提示第一条“[2019-07-19 09:51:46] 应援团 XXXXXXXXX 应援成功,获得 10 点亲密度 ”前出现。

虽然有报错，但是基本功能正常可使用。

**Comment by yjqiang** [comment]
docker 好久不修了  我对这货有点麻瓜… 你会搞这玩意儿么……

**Comment by yjqiang** [comment]
我最近改了ctrl.toml一个参数，我觉得可能不是docker问题。而是你没改参数

**Comment by PhoeniXuzoo** [comment]
> 我最近改了task.toml一个参数，我觉得可能不是docker问题。而是你没改参数send2medal_by_uid

修好了，我用的可能是旧版吧，task.toml内的参数是send2medal，改为send2medal_by_uid就好啦，辛苦了。
