### ISSUE TITLE
请问是否可以将默认房间自定义化，该如何设置？

### ISSUE THREAD

**Issue by HK418** [yjqiang/bili2.0#180]
conf/ctrl  内 修改了

# 默认监听房间号(用于打印弹幕功能等)
default_monitor_roomid = 23058

提示报错，是不是办法没用对？

**Comment by yjqiang** [comment]
你得告诉我报错信息啊

**Comment by HK418** [comment]
好的   只修改了此处。
默认监听房间号(用于打印弹幕功能等) default_monitor_roomid = 23058

以下是运行反馈
Traceback (most recent call last):
  File "run.py", line 47, in <module>
    dict_ctrl = conf_loader.read_ctrl()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\bili2.0-master\conf_loader.py", line 99, in read_ctrl
    return var.read_ctrl()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\bili2.0-master\conf_loader.py", line 73, in read_ctrl
    return self.toml_load(self.file_ctrl)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\bili2.0-master\conf_loader.py", line 42, in toml_load
    return toml.load(f)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\toml\decoder.py", line 134, in load
    return loads(f.read(), _dict, decoder)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\toml\decoder.py", line 227, in loads
    original, i)
toml.decoder.TomlDecodeError: Found invalid character in key name: '['. Try quoting the key name. (line 1 column 2 char 1)

**Comment by yjqiang** [comment]
用visual studio code这些改文件  不要记事本修改
