### ISSUE TITLE
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

### ISSUE THREAD

**Issue by Kjcdkcnjji** [yjqiang/bili2.0#20]
可用ip为 85 个
token有效期检查: 仍有效
Traceback (most recent call last):
  File "C:\Users\K1\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connection.py", line 171, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "C:\Users\K1\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\util\connection.py", line 79, in create_connection
    raise err
  File "C:\Users\K1\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\util\connection.py", line 69, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\K1\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Users\K1\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\K1\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\K1\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\K1\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\K1\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "C:\Users\K1\AppData\Local\Programs\Python\Python36\lib\http\client.py", line 964, in send
    self.connect()
  File "C:\Users\K1\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connection.py", line 196, in connect
    conn = self._new_conn()
  File "C:\Users\K1\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connection.py", line 180, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000027534EC3EF0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\K1\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\adapters.py", line 445, in send
    timeout=timeout
  File "C:\Users\K1\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\K1\AppData\Local\Programs\Python\Python36\lib\site-packages\urllib3\util\retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='47.95.255.188', port=5000): Max retries exceeded with url: /code (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000027534EC3EF0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\0.py", line 39, in <module>
    users = [User(i, user_info, dict_bili, task_control, True) for i, user_info in enumerate(dict_user['users'])]
  File ".\0.py", line 39, in <listcomp>
    users = [User(i, user_info, dict_bili, task_control, True) for i, user_info in enumerate(dict_user['users'])]
  File "C:\Users\K1\Desktop\K1\user.py", line 35, in __init__
    self.login()
  File "C:\Users\K1\Desktop\K1\user.py", line 122, in login
    response = self.webhub.captcha_login(url_username, url_password)
  File "C:\Users\K1\Desktop\K1\web_hub.py", line 350, in captcha_login
    captcha = cnn_captcha(tmp1)
  File "C:\Users\K1\Desktop\K1\web_hub.py", line 26, in cnn_captcha
    rsp = requests.post(url, data=data)
  File "C:\Users\K1\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "C:\Users\K1\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\K1\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\K1\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\K1\AppData\Local\Programs\Python\Python36\lib\site-packages\requests\adapters.py", line 513, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='47.95.255.188', port=5000): Max retries exceeded with url: /code (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000027534EC3EF0>: Failed to establish a new connection: [WinError 10061] 由于目 标计算机积极拒绝，无法连接。',))
PS C:\Users\K1\Desktop\K1>

**Comment by yjqiang** [comment]
这是原分支作者验证码机器挂了。。。
