### ISSUE TITLE
运行run.py时报错，python 3.8

### ISSUE THREAD

**Issue by ZTR05** [yjqiang/bili2.0#205]
**再确认一次 issue 题目**
请记得把 issue 标题改成问题描述的概述，而不是简单的一句话，《电脑开不了了》、《闪退了》、《救命啊》这些

**问题描述**
尽量详细叙述发生时间等
运行后出现问题，无法正常运行
**截图或者视频或者报错文字**
截图请务必把名字等信息打码
`C:\Users\Terry\Desktop\BILIBILILIVE>python run.py
Traceback (most recent call last):
  File "run.py", line 48, in <module>
    dict_task = conf_loader.read_task()
  File "C:\Users\Terry\Desktop\BILIBILILIVE\conf_loader.py", line 103, in read_task
    return var.read_task()
  File "C:\Users\Terry\Desktop\BILIBILILIVE\conf_loader.py", line 76, in read_task
    return self.toml_load(self.file_task)
  File "C:\Users\Terry\Desktop\BILIBILILIVE\conf_loader.py", line 42, in toml_load
    return toml.load(f)
  File "C:\Users\Terry\AppData\Local\Programs\Python\Python38\lib\site-packages\toml\decoder.py", line 134, in load
    return loads(f.read(), _dict, decoder)
  File "C:\Users\Terry\AppData\Local\Programs\Python\Python38\lib\site-packages\toml\decoder.py", line 225, in loads
    raise TomlDecodeError("Found invalid character in key name: '" +
toml.decoder.TomlDecodeError: Found invalid character in key name: '['. Try quoting the key name. (line 1 column 2 char 1)`
**必要的系统信息描述等**
python 版本以及系统版本信息
python 3.8
Windows 10
**最近何时更新的脚本**
几天前还是几小时前
最新版本
**最后确认**
- [ √] 我仔细看了requirements.tx，确认里面的模块我都安装并及时更新了
- [√ ] 我代码上次更新时间距今没有超过 2 个月以上
- [ √] 我仔细阅读了 conf 里面的 sample 文件（包括user.sample.toml和ctrl.sample.toml），并发现如果发生了改动，及时更新了我的 toml 对应文件
- [ √] 我仔细检查了 readme 最近更新情况，并查看了最近更新内容

**Comment by yjqiang** [comment]
toml文件要用vscode这些编辑  不要用记事本

**Comment by yjqiang** [comment]
https://github.com/yjqiang/bili2.0/issues/180
