### ISSUE TITLE
一切按照教程走后报错了...Python 3.7 (64-bit)版本

### ISSUE THREAD

**Issue by z664359671** [yjqiang/bili2.0#216]
C:\Users\66435>cd C:\Users\66435\Desktop\bili2.0-master

C:\Users\66435\Desktop\bili2.0-master>python run.py
Traceback (most recent call last):
  File "run.py", line 44, in <module>
    dict_user = conf_loader.read_user()
  File "C:\Users\66435\Desktop\bili2.0-master\conf_loader.py", line 95, in read_user
    return var.read_user()
  File "C:\Users\66435\Desktop\bili2.0-master\conf_loader.py", line 70, in read_user
    return self.toml_load(self.file_user)
  File "C:\Users\66435\Desktop\bili2.0-master\conf_loader.py", line 42, in toml_load
    return toml.load(f)
  File "C:\Users\66435\AppData\Local\Programs\Python\Python37\lib\site-packages\toml\decoder.py", line 134, in load
    return loads(f.read(), _dict, decoder)
  File "C:\Users\66435\AppData\Local\Programs\Python\Python37\lib\site-packages\toml\decoder.py", line 227, in loads
    original, i)
toml.decoder.TomlDecodeError: Found invalid character in key name: '['. Try quoting the key name. (line 1 column 2 char 1)

**Comment by pjy612** [comment]
配置文件格式不对，别用记事本。

用VSCode 或者 Notepad++等编辑器 编辑。
