### ISSUE TITLE
刚下载的文件运行报错

### ISSUE THREAD

**Issue by houxinxin** [yjqiang/bili2.0#231]
Traceback (most recent call last):
  File "run.py", line 44, in <module>
    dict_user = conf_loader.read_user()
  File "E:\360安全浏览器下载\bili2.0-master (1)\bili2.0-master\conf_loader.py", line 95, in read_user
    return var.read_user()
  File "E:\360安全浏览器下载\bili2.0-master (1)\bili2.0-master\conf_loader.py", line 70, in read_user
    return self.toml_load(self.file_user)
  File "E:\360安全浏览器下载\bili2.0-master (1)\bili2.0-master\conf_loader.py", line 42, in toml_load
    return toml.load(f)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\toml\decoder.py", line 134, in load
    return loads(f.read(), _dict, decoder)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\toml\decoder.py", line 227, in loads
    original, i)
toml.decoder.TomlDecodeError: Found invalid character in key name: '['. Try quoting the key name. (line 1 column 2 char 1)

**Comment by yjqiang** [comment]
https://github.com/yjqiang/bili2.0/issues/39
一模一样。。。

**Comment by houxinxin** [comment]
??????????????为啥关闭

**Comment by yjqiang** [comment]
一模一样的老问题 我显然不会重复回答了啊
