### ISSUE TITLE
运行run.py toml报错

### ISSUE THREAD

**Issue by KyuShiki** [yjqiang/bili2.0#264]
我按照步骤搭建了环境，conf下的文件是使用Notepad++编辑的，之后运行run.py会报错，内容如下：

C:\Users\KyuShiki\Desktop\Kyu\bili2.0>python run.py
Traceback (most recent call last):
  File "C:\Users\KyuShiki\AppData\Local\Programs\Python\Python38\lib\site-packages\toml\decoder.py", line 455, in loads
    ret = decoder.load_line(line, currentlevel, multikey,
  File "C:\Users\KyuShiki\AppData\Local\Programs\Python\Python38\lib\site-packages\toml\decoder.py", line 725, in load_line
    value, vtype = self.load_value(pair[1], strictly_valid)
  File "C:\Users\KyuShiki\AppData\Local\Programs\Python\Python38\lib\site-packages\toml\decoder.py", line 832, in load_value
    raise ValueError("This float doesn't have a leading "
ValueError: This float doesn't have a leading digit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 49, in <module>
    dict_ctrl = conf_loader.read_ctrl()
  File "C:\Users\KyuShiki\Desktop\Kyu\bili2.0\conf_loader.py", line 99, in read_ctrl
    return var.read_ctrl()
  File "C:\Users\KyuShiki\Desktop\Kyu\bili2.0\conf_loader.py", line 73, in read_ctrl
    return self.toml_load(self.file_ctrl)
  File "C:\Users\KyuShiki\Desktop\Kyu\bili2.0\conf_loader.py", line 42, in toml_load
    return toml.load(f)
  File "C:\Users\KyuShiki\AppData\Local\Programs\Python\Python38\lib\site-packages\toml\decoder.py", line 134, in load
    return loads(f.read(), _dict, decoder)
  File "C:\Users\KyuShiki\AppData\Local\Programs\Python\Python38\lib\site-packages\toml\decoder.py", line 458, in loads
    raise TomlDecodeError(str(err), original, pos)
toml.decoder.TomlDecodeError: This float doesn't have a leading digit (line 24 column 1 char 545)

我仔细查看了Issus，发现其他人运行run.py出现报错的原因都是conf文件使用记事本编辑造成的，而和我这个问题相符的只有#149同样是toml.decoder.TomlDecodeError: This float doesn't have a leading digit，我按照作者大大的回答检查了task.toml文件，找不到问题所在，之后我尝试将task.sample.toml原封不动的编辑成task.toml，也会产生同样的报错，后来我又在GitHub上找到了toml原作者发布的toml相关文件并覆盖了原文件，仍然会产生报错：
C: \Users \KyuShiki \Desktop \Kyu\bili2. 0>python run. py
Traceback (most recent call last) :
File" run. py，line 8，in <module>
import conf_ 1 oader
File" C: \Users \KyuShiki \Desktop \Kyu \bili2.0\conf_ loader. py'，line 3，in <module>
import toml
File" C: \Users \KyuShiki \AppData \Local \Programs \Py thon \Python38\1ib\site- packages\toml\ init_ . py，line 6，in <module
from toml import encoder
File” C: \Users \KyuShiki \AppData \Local \Programs \Python \Python38\lib\site-packages\toml \encoder. py'，line 6, in <modu1e>
from toml. decoder import Inl ineTableDict
File” C: \Users \KyuShiki \AppData \Local \Programs \Python \Python38\lib\si te-packages \toml \decoder. py'，line 1520
elif (pair[0][0] ==
or pair[0][0] == "")
and \
SyntaxError: invalid syntax 

小白第一次接触这些，劳烦作者大大帮我说明一下问题在哪？（我看到作者您被这些小白问题烦到的情况了hhh，但我真的没有其他解决办法了...）

**Comment by yjqiang** [comment]
是`ctrl.toml`报错，你检查错文件了

**Comment by KyuShiki** [comment]
感谢大佬解答，我把24行（实物抽奖）开关由true改成了false，之后再次运行按照错误指示是27行（动态抽奖）把true改成false后是29行（立即参与），将true全部改为false之后可以正常运行了~
一开始是有点贪心和好奇的，所以我就全部填写了true，想请教您一下为什么我填写true就会产生上述内容的报错呢？

还有就是我运行run.py反馈的内容除了正常文字信息外还有不少代码，这是正常现象吗？

举例：
[2020-02-01 18:52:07] check_results:
# <class 'tasks.live_daily_job.HeartBeatTask'>
# ((-2, (0, 30)),)
[2020-02-01 18:52:07] check_results:
# <class 'tasks.live_daily_job.RecvHeartGiftTask'>
# ((-2, (0, 30)),)
[2020-02-01 18:52:07] check_results:
# <class 'tasks.live_daily_job.OpenSilverBoxTask'>
# ((-2, (0, 30)),)
[2020-02-01 18:52:07] check_results:
# <class 'tasks.live_daily_job.RecvDailyBagTask'>
# ((-2, (0, 30)),)
[2020-02-01 18:52:07] check_results:
# <class 'tasks.live_daily_job.SignTask'>
# ((-2, (0, 30)),)
[2020-02-01 18:52:07] check_results:
# <class 'tasks.live_daily_job.WatchTvTask'>
# ((-2, (0, 30)),)
[2020-02-01 18:52:07] check_results:
# <class 'tasks.live_daily_job.SignFansGroupsTask'>
# ((-2, (0, 30)),)
[2020-02-01 18:52:07] check_results:
# <class 'tasks.live_daily_job.ExchangeSilverCoinTask'>
# ((-2, (0, 30)),)
[2020-02-01 18:52:07] check_results:
# <class 'tasks.main_daily_job.JudgeCaseTask'>
# ((-2, (0, 30)),)
[2020-02-01 18:52:07] check_results:
# <class 'tasks.manga_daily_job.MangaSignTask'>
# ((-2, (0, 30)),)
[2020-02-01 18:52:07] check_results:
# <class 'tasks.manga_daily_job.ShareComicTask'>
# ((-2, (0, 30)),)
[2020-02-01 18:52:07] check_results:
# <class 'tasks.main_daily_job.DahuiyuanTask'>
# ((-2, (0, 30)),)
[2020-02-01 18:52:07] -1号数据连接进入房间（23058）
[2020-02-01 18:52:07] 5号数据连接选择房间（78901）
[2020-02-01 18:52:07] 2号数据连接选择房间（5096）
[2020-02-01 18:52:07] 5号数据连接进入房间（78901）
[2020-02-01 18:52:07] 3号数据连接选择房间（313285）
[2020-02-01 18:52:07] check_results:
# <class 'tasks.live_daily_job.SendGiftTask'>
# ((-2, (0, 30), {6: 10.0, 4: 52.0, 10: 199.0, 9: 45.0, 121: 2.0, 30054: 50.0, 30085: 1.0, 30146: 2.5, 30247: 10.0, 30248: 1000.0, 120: 1.0, 30256: 1000.0, 30254: 10.0, 30295: 1.0, 1: 1.0, 30444: 1.0, 30458: 99.0, 30475: 99.0, 30501: 100.0, 30502: 100.0}),)
[2020-02-01 18:52:07] 2号数据连接进入房间（5096）
[2020-02-01 18:52:07] 1号数据连接选择房间（23058）
[2020-02-01 18:52:07] 3号数据连接进入房间（313285）
[2020-02-01 18:52:07] 1号数据连接进入房间（23058）
[2020-02-01 18:52:08] check_results:
# <class 'tasks.main_daily_job.BiliMainTask'>
# ((-2, (0, 30), ['85852078', '85781372', '85734058', '85669737', '85564554', '85621335', '85880712', '85854904', '85440373', '85628139', '85925894', '85760486', '79962257', '85836050', '85339970', '85440800', '85865474', '83484866', '85750244', '85665195', '85796491', '85848351', '64794511', '85837450', '85501649', '85651734', '85542896', '85576992', '85888090', '85966811', '85468826', '85890627', '85882423', '85709208', '85606424', '85772711', '85487162', '85760756', '85590030', '85604874', '85847123', '85859818', '85942726', '85211830', '82933153', '85377553', '85868779', '85593880', '85252072', '85887656', '85368449', '85682739', '85751585', '85688662', '85664023', '85536015', '85923709', '85831151', '85917933', '85054372', '84887919', '85792473', '85804184', '85859772', '85844890', '85231049', '85768445', '85798362', '85720592', '85946972', '85766577', '85772475', '85770824', '85535720', '78976165', '85936905', '85394121', '85878561', '85798486', '85804340', '85423961', '85845658', '85756748', '85691068', '85743252', '85819870', '85946419', '85127244', '85549192', '83711824', '78977736', '85462204', '84557590', '85460305', '85760587', '83268998', '85605106', '85782163', '85524412', '85420110', '85853211', '85873993', '85734125', '85864567']),)
[2020-02-01 18:52:08] 6号数据连接选择房间（12276230）
[2020-02-01 18:52:08] 4号数据连接选择房间（21701615）
[2020-02-01 18:52:08] 6号数据连接进入房间（12276230）
[2020-02-01 18:52:08] 4号数据连接进入房间（21701615）


[2020-02-01 18:55:51] 确认获取到小电视抽奖 685002
[2020-02-01 18:55:51] check_results:
# <class 'tasks.tv_raffle_handler.TvRaffleJoinTask'>
# [(-2, (117, 167), 1156962, 685002, 'small_tv')]
[2020-02-01 18:55:52] 小电视(684997)的参与结果: 辣条X5 (用户id:0 名字:xxx)
[2020-02-01 18:56:02] 小电视(684998)的参与结果: 辣条X5 (用户id:0 名字:xxx)
[2020-02-01 18:56:03] 3号数据连接检测到21721414 的小电视
[2020-02-01 18:56:06] 确认获取到小电视抽奖 685003
[2020-02-01 18:56:06] check_results:
# <class 'tasks.tv_raffle_handler.TvRaffleJoinTask'>
# [(-2, (57, 107), 21721414, 685003, 'GIFT_30465')]
[2020-02-01 18:56:18] 小电视(684996)的参与结果: 辣条X5 (用户id:0 名字:xxx)
[2020-02-01 18:56:22] 小电视(684999)的参与结果: 辣条X1 (用户id:0 名字:xxx)
[2020-02-01 18:56:25] 小电视(684993)的参与结果: 辣条X5 (用户id:0 名字:xxx)
[2020-02-01 18:56:58] 小电视(685001)的参与结果: 奥利给头衔X1 (用户id:0 名字:xxx)
[2020-02-01 18:57:24] 4号数据连接检测到21701615 的舰长
<class 'aiohttp.client_exceptions.ServerDisconnectedError'>  https://api.live.bilibili.com/xlive/lottery-interface/v1/lottery/Check?roomid=21701615
[2020-02-01 18:57:31] 确认获取到大航海抽奖 1968206
[2020-02-01 18:57:31] check_results:
# <class 'tasks.guard_raffle_handler.GuardRafflJoinTask'>
# [(-2, (0, 240), 21701615, 1968206)]
[2020-02-01 18:57:34] 心跳包(5分钟左右间隔){'code': 0, 'msg': 'success', 'message': 'success', 'data': {'giftlist': []}} {'code': 0, 'msg': 'success', 'message': 'success', 'data': {'giftlist': []}} (用户id:0 名字:xxx)

**Comment by yjqiang** [comment]
> 感谢大佬解答，我把24行（实物抽奖）开关由true改成了false，之后再次运行按照错误指示是27行（动态抽奖）把true改成false后是29行（立即参与），将true全部改为false之后可以正常运行了~
> 一开始是有点贪心和好奇的，所以我就全部填写了true，想请教您一下为什么我填写true就会产生上述内容的报错呢？

可能是你 true拼写错误，不可能true就报错的。

> 还有就是我运行run.py反馈的内容除了正常文字信息外还有不少代码，这是正常现象吗？
 
正常

**Comment by KyuShiki** [comment]
真的万分感谢，我重新弄了一遍已经没有问题了！这篇Issue我就先关闭啦~

> 感谢大佬解答，我把24行（实物抽奖）开关由true改成了false，之后再次运行按照错误指示是27行（动态抽奖）把true改成false后是29行（立即参与），将true全部改为false之后可以正常运行了~
> 一开始是有点贪心和好奇的，所以我就全部填写了true，想请教您一下为什么我填写true就会产生上述内容的报错呢？
> 
> 可能是你 true拼写错误，不可能true就报错的。
> 
> 还有就是我运行run.py反馈的内容除了正常文字信息外还有不少代码，这是正常现象吗？
> 
> 正常
