### ISSUE TITLE
return loads(f.read(), _dict, decoder)

### ISSUE THREAD

**Issue by holll** [yjqiang/bili2.0#271]
python版本：Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)] on win32
系统版本：win10企业版
运行环境：云服务器

以下为运行代码

C:\Users\Administrator\Desktop\bili2.0-master>python run.py
Traceback (most recent call last):
  File "run.py", line 48, in <module>
    dict_ctrl = conf_loader.read_ctrl()
  File "C:\Users\Administrator\Desktop\bili2.0-master\conf_loader.py", line 99, in read_ctrl
    return var.read_ctrl()
  File "C:\Users\Administrator\Desktop\bili2.0-master\conf_loader.py", line 73, in read_ctrl
    return self.toml_load(self.file_ctrl)
  File "C:\Users\Administrator\Desktop\bili2.0-master\conf_loader.py", line 42, in toml_load
    return toml.load(f)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\toml\decoder.py", line 134, in load
    return loads(f.read(), _dict, decoder)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\toml\decoder.py", line 225, in loads
    raise TomlDecodeError("Found invalid character in key name: '" +
toml.decoder.TomlDecodeError: Found invalid character in key name: '['. Try quoting the key name. (line 1 column 2 char 1)

**Comment by yjqiang** [comment]
https://github.com/yjqiang/bili2.0/issues/180
