### ISSUE TITLE
。。

### ISSUE THREAD

**Issue by yjqiang** [yjqiang/bili2.0#30]
Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x116553cf8>
transport: <_SelectorSocketTransport fd=357 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/private/var/mobile/Containers/Shared/AppGroup/383B28C1-6DCF-40D8-AB53-B5F7548B7F79/Pythonista3/Documents/site-packages-3/aiohttp/client.py", line 391, in _request
    await resp.start(conn)
  File "/private/var/mobile/Containers/Shared/AppGroup/383B28C1-6DCF-40D8-AB53-B5F7548B7F79/Pythonista3/Documents/site-packages-3/aiohttp/client_reqrep.py", line 770, in start
    self._continue = None
  File "/private/var/mobile/Containers/Shared/AppGroup/383B28C1-6DCF-40D8-AB53-B5F7548B7F79/Pythonista3/Documents/site-packages-3/aiohttp/helpers.py", line 673, in __exit__
    raise asyncio.TimeoutError from None
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/containers/Bundle/Application/84DF3BDF-B442-41B6-93B3-AB45EDA9E5FC/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/asyncio/sslproto.py", line 640, in _process_write_backlog
    ssldata = self._sslpipe.shutdown(self._finalize)
  File "/var/containers/Bundle/Application/84DF3BDF-B442-41B6-93B3-AB45EDA9E5FC/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/asyncio/sslproto.py", line 156, in shutdown
    ssldata, appdata = self.feed_ssldata(b'')
  File "/var/containers/Bundle/Application/84DF3BDF-B442-41B6-93B3-AB45EDA9E5FC/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/asyncio/sslproto.py", line 220, in feed_ssldata
    self._sslobj.unwrap()
  File "/var/containers/Bundle/Application/84DF3BDF-B442-41B6-93B3-AB45EDA9E5FC/Pythonista3.app/Frameworks/Py3Kit.framework/pylib/ssl.py", line 692, in unwrap
    return self._sslobj.shutdown()
ssl.SSLError: [SSL] called a function you should not call (_ssl.c:2299)

**Comment by yjqiang** [comment]
openssl老问题
https://github.com/aio-libs/aiohttp/issues/3393#issuecomment-441608367
