### ISSUE TITLE
No module named 'danmu_abc'

### ISSUE THREAD

**Issue by bilibilifei** [yjqiang/bili2.0#304]
3月10日下载的最新文件，启动后就成这样
C:\Users\Adminzyc\Desktop\bili2.0-master>python run.py
Traceback (most recent call last):
  File "run.py", line 36, in <module>
    from danmu.bili_danmu_monitor import DanmuPrinter, DanmuRaffleMonitor
  File "C:\Users\Adminzyc\Desktop\bili2.0-master\danmu\bili_danmu_monitor.py", line 8, in <module>
    from danmu.bili_abc import bili_danmu
  File "C:\Users\Adminzyc\Desktop\bili2.0-master\danmu\bili_abc\bili_danmu.py", line 5, in <module>
    from danmu_abc import WsConn, Client
ModuleNotFoundError: No module named 'danmu_abc'
大佬帮忙看看

**Comment by yjqiang** [comment]
requirements.txt有添加新的依赖  pip install就行
