### ISSUE TITLE
大部分可以正常运行，但是中间会有下面的报错信息

### ISSUE THREAD

**Issue by GOOD-AN** [yjqiang/bili2.0#326]
Job processing failed
job: <Job coro=<<coroutine object Notifier._unique_work at 0x00000211F12C9448>>>
Traceback (most recent call last):
  File "C:\Users\wjt\Desktop\1\bili2.0-master\notifier.py", line 106, in _unique_work
    result = await func(user, *args, **kwargs)
  File "C:\Users\wjt\Desktop\1\bili2.0-master\tasks\main_daily_job.py", line 224, in work
    aid = random.choice(aids)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\random.py", line 261, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
IndexError: Cannot choose from an empty sequence

**Comment by Twoleaf** [comment]
https://github.com/yjqiang/bili2.0/issues/325#issuecomment-603000145

**Comment by yjqiang** [comment]
https://github.com/yjqiang/bili2.0/issues/325
? 你重复发了呀

**Comment by GOOD-AN** [comment]
不好意思，我这边可能是卡掉了，以为没发出去。。。
