### ISSUE TITLE
运行报错\uxx

### ISSUE THREAD

**Issue by shoucandanghehe** [yjqiang/bili2.0#347]
运行时报错：
```
Task exception was never retrieved
future: <Task finished coro=<Client._job_main() done, defined at /usr/local/lib/python3.7/dist-packages/danmu_abc/client.py:63> exception=UnicodeDecodeError('utf-8', b'x\xdaD\x8e\xbdJCQ\x10\x84\xaf\x85\x8d\x95\xcf0\xf5\x14\xbb\xe7f\xcf\xcf\xed\x04\xc1*6bu\xbc\x88\x1e\r\x081\x16&UHag!X\xf8\x04\xbe\x80\xc4\xc2\xce\xb7\x91@|\x0b9!\x98e\x19\x18\xf6\x1bv\x9af\xef\xa09l\xea\xecW\x99\xa3\xdc\xdf\xa0\xc3\xf1\xd1\xe9\xf0\xfcrxv\x02\xe2n2z@\x97\xb3P\xe9\x8c\xeaC\x08N\x8dj\xd1\x9b\x98O\xdaz\xbfum4\xa1\x10\xd7\xe5j0*)\x80\xd5JO\xac\xde\x9e\xff\x17\xcc\x03uAR\x8aF\xac\xdf_\xd6_\xcb\x9f\xa7\x8f\xd5\xf2\xf5\xf7\xf3{\x1b\xa1\x8aH}\t\xf4\xcc=\xb3\xa30E\x1f\x93\tq1\x13io\xad"\xf5\x0cl\xb0\x1a\x9b\xcc\xc6c\xce1}D\xb7+H\x94):\xa8\x8a\x98K-\x16;t#\xd2/\xfe\x02\x00\x00\xff\xff{~G\xc5', 1, 2, 'invalid continuation byte')>Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/danmu_abc/client.py", line 65, in _job_main    if not await self._one_read():
  File "/root/dyh/danmu/bili_abc/bili_danmu.py", line 58, in _one_read
    if not self.parse_body(body, opt):
  File "/root/dyh/danmu/bili_abc/bili_danmu.py", line 68, in parse_body
    if not self.handle_danmu(json.loads(body.decode('utf-8'))):
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xda in position 1: invalid continuation byte
```
今天突然发现这个报错，以前并没有
系统Ubuntu19.10
python3.7.5
第三方模块版本为最新

**Comment by yjqiang** [comment]
更新最新版

**Comment by shoucandanghehe** [comment]
没看到代码有更新，抱歉
