### ISSUE TITLE
运行时报错

### ISSUE THREAD

**Issue by tpq95** [yjqiang/bili2.0#348]
**问题描述**
python run.py
报错：
`F:\bili2.0-master>python run.py
Traceback (most recent call last):
  File "run.py", line 36, in <module>
    from danmu.bili_danmu_monitor import DanmuPrinter, DanmuRaffleMonitor
  File "F:\bili2.0-master\danmu\bili_danmu_monitor.py", line 8, in <module>
    from danmu.bili_abc import bili_danmu
  File "F:\bili2.0-master\danmu\bili_abc\bili_danmu.py", line 6, in <module>
    from danmu_abc import WsConn, Client
ModuleNotFoundError: No module named 'danmu_abc'`

**最近何时更新的脚本**
4:40pm 更新的

**Comment by yjqiang** [comment]
看requirements.txt

**Comment by tpq95** [comment]
不好意思，原来加了requirement。谢谢回答。
