### ISSUE TITLE
我尝试封装成exe文件报错提示如下

### ISSUE THREAD

**Issue by lNeverl** [yjqiang/bili2.0#353]
**再确认一次 issue 题目**
请记得把 issue 标题改成问题描述的概述，而不是简单的一句话，《电脑开不了了》、《闪退了》、《救命啊》这些

**问题描述**
尽量详细叙述发生时间等

**截图或者视频或者报错文字**
截图请务必把名字等信息打码

**必要的系统信息描述等**
python 版本以及系统版本信息

**最近何时更新的脚本**
几天前还是几小时前

**最后确认**
- [ √] 我仔细看了requirements.tx，确认里面的模块我都安装并及时更新了
- [√ ] 我代码上次更新时间距今没有超过 2 个月以上
- [√ ] 我仔细阅读了 conf 里面的 sample 文件（包括user.sample.toml和ctrl.sample.toml），并发现如果发生了改动，及时更新了我的 toml 对应文件
- [ √] 我仔细检查了 readme 最近更新情况，并查看了最近更新内容

--------------------------------

```
Traceback (most recent call last):
  File "run.py", line 40, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "d:\python\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "substance\monitor_substance_raffle.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "d:\python\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "tasks\substance_raffle_handler.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "d:\python\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "substance\substance_raffle_sql.py", line 8, in <module>
sqlite3.OperationalError: unable to open database file
[11996] Failed to execute script run
```

这个错误是哪里出现问题了呢

**Comment by yjqiang** [comment]
我也不会封装exe……

**Comment by lNeverl** [comment]
> 我也不会封装exe……
但是报错的这个信息能不能看出一些蛛丝马迹啥的，我想尝试一下。

**Comment by yjqiang** [comment]
试试这个 https://github.com/yjqiang/bili2.0/pull/297/files

**Comment by lNeverl** [comment]
> 试试这个 https://github.com/yjqiang/bili2.0/pull/297/files

好的
