### ISSUE TITLE
出现此提示，重启程序也无效

### ISSUE THREAD

**Issue by GOOD-AN** [yjqiang/bili2.0#360]
![QQ图片20200417163139](https://user-images.githubusercontent.com/53306377/79549233-4d301500-80c9-11ea-97f1-3af7868cc872.png)

**Comment by GOOD-AN** [comment]
Traceback (most recent call last):
  File "C:\Users\wjt\Desktop\1\bili2.0-master\run.py", line 177, in <module>
    loop.run_until_complete(asyncio.wait(tasks + other_tasks))
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\asyncio\base_events.py", line 566, in run_until_complete
    self.run_forever()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\asyncio\base_events.py", line 534, in run_forever
    self._run_once()
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\asyncio\base_events.py", line 1735, in _run_once
    event_list = self._selector.select(timeout)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\selectors.py", line 323, in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\selectors.py", line 314, in _select
    r, w, x = select.select(r, w, w, timeout)
OSError: [WinError 10038] 在一个非套接字上尝试了一个操作。

**Comment by Twoleaf** [comment]
https://github.com/yjqiang/bili2.0/issues/85

**Comment by Kongxiangzhouye** [comment]
+1

**Comment by lNeverl** [comment]
解决了吗大大

**Comment by giorgiasistina** [comment]
我今天下午也碰到了，还以为是我一个人的问题。
改用python3.8似乎可以解决，但收益效率似乎低了不少……

**Comment by SekiBetu** [comment]
这python安装位置可真独特，怎么还安装在vs的目录里的

**Comment by GOOD-AN** [comment]
> 这python安装位置可真独特，怎么还安装在vs的目录里的

因为开始本来就是在vs2019下安装的python

**Comment by GOOD-AN** [comment]
> 解决了吗大大

经过观察，出现这种问题隔天就好了。。。

**Comment by lNeverl** [comment]
> > 解决了吗大大
> 
> 经过观察，出现这种问题隔天就好了。。。

我今天也没事了
