### ISSUE TITLE
SyntaxError: invalid character in identifier

### ISSUE THREAD

**Issue by reloader91** [yjqiang/bili2.0#38]
Traceback (most recent call last):
  File "0.py", line 3, in <module>
    from webhub.web_hub import WebHub, HostWebHub
  File "/home/reloader/bili2.0/webhub/web_hub.py", line 2, in <module>
    from webhub.bili_web_hub import BiliWebHub, HostBiliWebHub
  File "/home/reloader/bili2.0/webhub/bili_web_hub.py", line 147
    'csrf_token': self.dict_bili['csrf']，
                                        ^
SyntaxError: invalid character in identifier
似乎那个逗号打成全角符了

**Comment by yjqiang** [comment]
我这里运行正常呀……你是不是自己改动的？

**Comment by yjqiang** [comment]
fix 了  的确 thx
