### ISSUE TITLE
脚本登陆一直失败，自己手动填入cookie等信息报如下错误

### ISSUE THREAD

**Issue by KNulL0** [yjqiang/bili2.0#416]
```
# <class 'tasks.login.LoginTask'>
# ((-2, None),)
<class 'concurrent.futures._base.TimeoutError'>  http://152.32.186.69:19951/captcha/v1
```
登陆失败的

自己手动填写
```
[2020-07-30 22:30:17] check_results:
# <class 'tasks.login.LoginTask'>
# ((-2, None),)
Traceback (most recent call last):
  File "run.py", line 103, in <module>
    loop.run_until_complete(notifier.exec_task(LoginTask))
  File "C:\Python37\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "C:\Users\yuan\Desktop\新建文件夹\bili2.0\notifier.py", line 276, in exec_task
    return await var_notifier.exec_task(task, *args, **kwargs)
  File "C:\Users\yuan\Desktop\新建文件夹\bili2.0\notifier.py", line 256, in exec_task
    return await handle_works(task, handle_work, handle_unique, func_work, check_results, need_results)
  File "C:\Users\yuan\Desktop\新建文件夹\bili2.0\notifier.py", line 166, in _wait
    await handle_work(handle_unique, user, task, func_work, *args)
  File "C:\Users\yuan\Desktop\新建文件夹\bili2.0\notifier.py", line 140, in run_forced_func
    return await func(*args, **kwargs)
  File "C:\Users\yuan\Desktop\新建文件夹\bili2.0\notifier.py", line 119, in _multi_work
    return await func(user, *args, **kwargs)
  File "C:\Users\yuan\Desktop\新建文件夹\bili2.0\tasks\login.py", line 20, in work
    await LoginTask.handle_login_status(user)
  File "C:\Users\yuan\Desktop\新建文件夹\bili2.0\tasks\login.py", line 26, in handle_login_status
    if not (await LoginTask.is_token_usable(user)):
  File "C:\Users\yuan\Desktop\新建文件夹\bili2.0\tasks\login.py", line 36, in is_token_usable
    json_rsp = await LoginReq.is_token_usable(user)
  File "C:\Users\yuan\Desktop\新建文件夹\bili2.0\reqs\login.py", line 65, in is_token_usable
    key, value = param.split('=')
ValueError: not enough values to unpack (expected 2, got 1)
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000021DD4A05888>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000021DD4A05C08>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x0000021DD4A04948>
```

**最近何时更新的脚本**
最新

**最后确认**
- [ ] 我仔细看了requirements.tx，确认里面的模块我都安装并及时更新了
- [ ] 我代码上次更新时间距今没有超过 2 个月以上
- [ ] 我仔细阅读了 conf 里面的 sample 文件（包括user.sample.toml和ctrl.sample.toml），并发现如果发生了改动，及时更新了我的 toml 对应文件
- [ ] 我仔细检查了 readme 最近更新情况，并查看了最近更新内容

**Comment by yjqiang** [comment]
自己填写你写不了token这些。。。只写cookie没用

**Comment by yjqiang** [comment]
根据提示信息，你 cookie 写错了格式，应该是
```py
bili_jct=xxxxxxxxxxxxxxxxxxxxxxxxxxxx;DedeUserID=10xxxxxxxxx;DedeUserID__ckMd5=xxxxxxxxxxxxxx;sid=xxxxxxxxxxxxxx;SESSDATA=xxxxxxxxxxxxxxxxxxx
```

**Comment by KNulL0** [comment]
确认了一下是这个格式，，我把loop.run_until_complete(notifier.exec_task(LoginTask))这行代码注释，正常运行了。也能做日常任务。

**Comment by bbbgggq** [comment]
> 确认了一下是这个格式，，我把loop.run_until_complete(notifier.exec_task(LoginTask))这行代码注释，正常运行了。也能做日常任务。

请问这个是在哪个文件

**Comment by Jutean** [comment]
> > 确认一下是这个格式，，我把loop.run_until_complete(notifier.exec_task(LoginTask))这行代码注释，正常运行了。也可以做日常任务。
> 
> 这个是在哪个文件

run.py

**Comment by Jutean** [comment]
> 确认一下是这个格式，，我把loop.run_until_complete(notifier.exec_task(LoginTask))这行代码注释，正常运行了。也可以做日常任务。

关闭这个会少些啥？
