### ISSUE TITLE
新报错

### ISSUE THREAD

**Issue by handsomebubu** [yjqiang/bili2.0#42]
Task exception was never retrieved
future: <Task finished coro=<Notifier.__exec_one_step() done, defined at E:\bilibili help\bili2.0-master\notifier.py:42> exception=RuntimeError('Task <Task pending coro=<Notifier.__exec_one_step() running at E:\\bilibili help\\bili2.0-master\\notifier.py:46>> got Future <Future pending> attached to a different loop',)>
Traceback (most recent call last):
  File "E:\bilibili help\bili2.0-master\notifier.py", line 46, in __exec_one_step
    results = await self.notify(id, func, *args)
  File "E:\bilibili help\bili2.0-master\notifier.py", line 20, in notify
    result = await self.users[id].accept(func, *args)
  File "E:\bilibili help\bili2.0-master\user.py", line 113, in accept
    return await func(self, *args)
  File "E:\bilibili help\bili2.0-master\tasks\live_daily_job.py", line 276, in send_gift
    await SendGiftTask.send_medal_gift(user)
  File "E:\bilibili help\bili2.0-master\tasks\live_daily_job.py", line 231, in send_medal_gift
    medals = await SendGiftTask.fetch_wearing_medal(user)
  File "E:\bilibili help\bili2.0-master\tasks\live_daily_job.py", line 189, in fetch_wearing_medal
    json_rsp = await user.req_s(SendGiftReq.fetch_wearing_medal, user)
  File "E:\bilibili help\bili2.0-master\user.py", line 82, in req_s
    rsp = await func(*args)
  File "E:\bilibili help\bili2.0-master\reqs\live_daily_job.py", line 103, in fetch_wearing_medal
    json_rsp = await user.bililive_session.request_json('POST', url, data=data, headers=user.dict_bili['pcheaders'])
  File "E:\bilibili help\bili2.0-master\web_session.py", line 57, in request_json
    async with sem:
  File "E:\Program Files\Python36\lib\asyncio\locks.py", line 79, in __aenter__
    yield from self.acquire()
  File "E:\Program Files\Python36\lib\asyncio\locks.py", line 468, in acquire
    yield from fut
RuntimeError: Task <Task pending coro=<Notifier.__exec_one_step() running at E:\bilibili help\bili2.0-master\notifier.py:46>> got Future <Future pending> attached to a different loop
Task exception was never retrieved
future: <Task finished coro=<Notifier.__exec_one_step() done, defined at E:\bilibili help\bili2.0-master\notifier.py:42> exception=RuntimeError('Task <Task pending coro=<Notifier.__exec_one_step() running at E:\\bilibili help\\bili2.0-master\\notifier.py:46>> got Future <Future pending> attached to a different loop',)>
Traceback (most recent call last):
  File "E:\bilibili help\bili2.0-master\notifier.py", line 46, in __exec_one_step
    results = await self.notify(id, func, *args)
  File "E:\bilibili help\bili2.0-master\notifier.py", line 20, in notify
    result = await self.users[id].accept(func, *args)
  File "E:\bilibili help\bili2.0-master\user.py", line 113, in accept
    return await func(self, *args)
  File "E:\bilibili help\bili2.0-master\tasks\live_daily_job.py", line 276, in send_gift
    await SendGiftTask.send_medal_gift(user)
  File "E:\bilibili help\bili2.0-master\tasks\live_daily_job.py", line 231, in send_medal_gift
    medals = await SendGiftTask.fetch_wearing_medal(user)
  File "E:\bilibili help\bili2.0-master\tasks\live_daily_job.py", line 189, in fetch_wearing_medal
    json_rsp = await user.req_s(SendGiftReq.fetch_wearing_medal, user)
  File "E:\bilibili help\bili2.0-master\user.py", line 82, in req_s
    rsp = await func(*args)
  File "E:\bilibili help\bili2.0-master\reqs\live_daily_job.py", line 103, in fetch_wearing_medal
    json_rsp = await user.bililive_session.request_json('POST', url, data=data, headers=user.dict_bili['pcheaders'])
  File "E:\bilibili help\bili2.0-master\web_session.py", line 57, in request_json
    async with sem:
  File "E:\Program Files\Python36\lib\asyncio\locks.py", line 79, in __aenter__
    yield from self.acquire()
  File "E:\Program Files\Python36\lib\asyncio\locks.py", line 468, in acquire
    yield from fut
RuntimeError: Task <Task pending coro=<Notifier.__exec_one_step() running at E:\bilibili help\bili2.0-master\notifier.py:46>> got Future <Future pending> attached to a different loop
{'code': 25005, 'message': '请成为风纪委员后再试', 'ttl': 1}
本次未获取到案件
True True 50 True
Task exception was never retrieved
future: <Task finished coro=<Notifier.__exec_one_step() done, defined at E:\bilibili help\bili2.0-master\notifier.py:42> exception=RuntimeError('Task <Task pending coro=<Notifier.__exec_one_step() running at E:\\bilibili help\\bili2.0-master\\notifier.py:46>> got Future <Future pending> attached to a different loop',)>
Traceback (most recent call last):
  File "E:\bilibili help\bili2.0-master\notifier.py", line 46, in __exec_one_step
    results = await self.notify(id, func, *args)
  File "E:\bilibili help\bili2.0-master\notifier.py", line 20, in notify
    result = await self.users[id].accept(func, *args)
  File "E:\bilibili help\bili2.0-master\user.py", line 113, in accept
    return await func(self, *args)
  File "E:\bilibili help\bili2.0-master\tasks\main_daily_job.py", line 126, in judge
    json_rsp = await user.req_s(JudgeCaseReq.fetch_case, user)
  File "E:\bilibili help\bili2.0-master\user.py", line 82, in req_s
    rsp = await func(*args)
  File "E:\bilibili help\bili2.0-master\reqs\main_daily_job.py", line 28, in fetch_case
    json_rsp = await user.other_session.request_json('POST', url, headers=user.dict_bili['pcheaders'], data=data)
  File "E:\bilibili help\bili2.0-master\web_session.py", line 57, in request_json
    async with sem:
  File "E:\Program Files\Python36\lib\asyncio\locks.py", line 79, in __aenter__
    yield from self.acquire()
  File "E:\Program Files\Python36\lib\asyncio\locks.py", line 468, in acquire
    yield from fut
RuntimeError: Task <Task pending coro=<Notifier.__exec_one_step() running at E:\bilibili help\bili2.0-master\notifier.py:46>> got Future <Future pending> attached to a different loop
开始赠送硬币

**Comment by yjqiang** [comment]
loop设置这里windows采用了另一个系列，但是websession会在import时被执行，所以，全局锁的loop用了老的loop

**Comment by yjqiang** [comment]
修改办法恶心了一点  https://docs.python.org/dev/whatsnew/3.8.html#asyncio
3.8会修复的，不要着急，大概一年后这行代码就不需要了
