### ISSUE TITLE
zhege

### ISSUE THREAD

**Issue by ShirokamiFubuki** [yjqiang/bili2.0#425]
Traceback (most recent call last):
  File "C:\bili2.0-master\run.py", line 9, in <module>
    import notifier
  File "C:\bili2.0-master\notifier.py", line 8, in <module>
    from user.user import User
ModuleNotFoundError: No module named 'user.user'; 'user' is not a package

**Comment by yjqiang** [comment]
全部删掉重下，之前的 user.py 文件我改动过
