### ISSUE TITLE
module 'attr.validators' has no attribute 'deep_iterable'

### ISSUE THREAD

**Issue by Love4Taylor** [yjqiang/bili2.0#68]
```
Traceback (most recent call last):
  File "run.py", line 31, in <module>
    from dyn.monitor_dyn_raffle import DynRaffleMonitor
  File "/home/love4taylor/scripts/bili2.0/dyn/monitor_dyn_raffle.py", line 5, in <module>
    from .bili_data_types import DynRaffleStatus, DynRaffleResults
  File "/home/love4taylor/scripts/bili2.0/dyn/bili_data_types.py", line 60, in <module>
    @attr.s(frozen=True)
  File "/home/love4taylor/scripts/bili2.0/dyn/bili_data_types.py", line 72, in DynRaffleResults
    validator=attr.validators.deep_iterable(
AttributeError: module 'attr.validators' has no attribute 'deep_iterable'
```

**Comment by someash** [comment]
在python里面输入pip install -U attrs

**Comment by wangmanv2** [comment]
卸载了以后 `toml `开始报错了
```
pi@raspberrypi:~/bili2.0 $ sudo pip3.7 install -U attrs
Collecting attrs
  Downloading https://files.pythonhosted.org/packages/23/96/d828354fa2dbdf216eaa7b7de0db692f12c234f7ef888cc14980ef40d1d2/attrs-19.1.0-py2.py3-none-any.whl
Installing collected packages: attrs
  Found existing installation: attrs 18.2.0
    Uninstalling attrs-18.2.0:
      Successfully uninstalled attrs-18.2.0
Successfully installed attrs-19.1.0
pi@raspberrypi:~/bili2.0 $ python3.7 /home/pi/bili2.0/run.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/toml/decoder.py", line 456, in loads
    multibackslash)
  File "/usr/local/lib/python3.7/site-packages/toml/decoder.py", line 725, in load_line
    value, vtype = self.load_value(pair[1], strictly_valid)
  File "/usr/local/lib/python3.7/site-packages/toml/decoder.py", line 805, in load_value
    self.load_inline_object(v, inline_object)
  File "/usr/local/lib/python3.7/site-packages/toml/decoder.py", line 624, in load_inline_object
    multibackslash)
  File "/usr/local/lib/python3.7/site-packages/toml/decoder.py", line 728, in load_line
    raise ValueError("Duplicate keys!")
ValueError: Duplicate keys!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/bili2.0/run.py", line 42, in <module>
    dict_ctrl = conf_loader.read_ctrl()
  File "/home/pi/bili2.0/conf_loader.py", line 93, in read_ctrl
    return var.read_ctrl()
  File "/home/pi/bili2.0/conf_loader.py", line 65, in read_ctrl
    dict_ctrl = toml.load(f)
  File "/usr/local/lib/python3.7/site-packages/toml/decoder.py", line 134, in load
    return loads(f.read(), _dict, decoder)
  File "/usr/local/lib/python3.7/site-packages/toml/decoder.py", line 458, in loads
    raise TomlDecodeError(str(err), original, pos)
toml.decoder.TomlDecodeError: Duplicate keys! (line 32 column 1 char 784)

```

**Comment by yjqiang** [comment]
@wangmanv2 请另开issue，你提到问题与本主题不相干。
