### ISSUE TITLE
toml运行的时候报错（ValueError: Duplicate keys!）

### ISSUE THREAD

**Issue by wangmanv2** [yjqiang/bili2.0#69]
内容
```
pi@raspberrypi:~ $ python3.7 ./bili2.0/run.py 
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/toml/decoder.py", line 456, in loads
    multibackslash)
  File "/usr/local/lib/python3.7/site-packages/toml/decoder.py", line 725, in load_line
    value, vtype = self.load_value(pair[1], strictly_valid)
  File "/usr/local/lib/python3.7/site-packages/toml/decoder.py", line 805, in load_value
    self.load_inline_object(v, inline_object)
  File "/usr/local/lib/python3.7/site-packages/toml/decoder.py", line 624, in load_inline_object
    multibackslash)
  File "/usr/local/lib/python3.7/site-packages/toml/decoder.py", line 728, in load_line
    raise ValueError("Duplicate keys!")
ValueError: Duplicate keys!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./bili2.0/run.py", line 42, in <module>
    dict_ctrl = conf_loader.read_ctrl()
  File "/home/pi/bili2.0/conf_loader.py", line 93, in read_ctrl
    return var.read_ctrl()
  File "/home/pi/bili2.0/conf_loader.py", line 65, in read_ctrl
    dict_ctrl = toml.load(f)
  File "/usr/local/lib/python3.7/site-packages/toml/decoder.py", line 134, in load
    return loads(f.read(), _dict, decoder)
  File "/usr/local/lib/python3.7/site-packages/toml/decoder.py", line 458, in loads
    raise TomlDecodeError(str(err), original, pos)
toml.decoder.TomlDecodeError: Duplicate keys! (line 32 column 1 char 787)
```

**Comment by yjqiang** [comment]
按照字面意思，是你ctrl.toml文件改错了东西，你自己看一看。如果还不行的话，就把这个文件上传。

**Comment by wangmanv2** [comment]
啊啊啊啊 其实报错很明显了，是我的问题，我在新功能的那个@好友的地方，打了两个相同的值。
