### ISSUE TITLE
最新动态抽奖更新（attrs）

### ISSUE THREAD

**Issue by a253208088** [yjqiang/bili2.0#72]
Traceback (most recent call last):
File "run.py", line 31, in 
from dyn.monitor_dyn_raffle import DynRaffleMonitor
File "D:\bili2.0-master\dyn\monitor_dyn_raffle.py", line 5, in 
from .bili_data_types import DynRaffleStatus, DynRaffleResults
File "D:\bili2.0-master\dyn\bili_data_types.py", line 60, in 
@attr.s(frozen=True)
File "D:\bili2.0-master\dyn\bili_data_types.py", line 72, in DynRaffleResults
validator=attr.validators.deep_iterable(
AttributeError: module 'attr.validators' has no attribute 'deep_iterable'
运行就这样 ,怎么搞大佬

**Comment by yjqiang** [comment]
https://github.com/yjqiang/bili2.0/issues/68#issuecomment-470492656
