### ISSUE TITLE
toml.TomlDecodeError: Found invalid character in key name: '['.

### ISSUE THREAD

**Issue by WashingtonBB56** [yjqiang/bili2.0#79]
Python 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 03:37:03) [MSC v.1900 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> 
================ RESTART: E:\PYTHON 3.6\bili2.0-master\run.py ================
Traceback (most recent call last):
  File "E:\PYTHON 3.6\bili2.0-master\conf_loader.py", line 89, in read_user
    return var.read_user()
  File "E:\PYTHON 3.6\bili2.0-master\conf_loader.py", line 60, in read_user
    dict_user = toml.load(f)
  File "E:\PYTHON 3.6\lib\site-packages\toml.py", line 108, in load
    return loads(f.read(), _dict)
  File "E:\PYTHON 3.6\lib\site-packages\toml.py", line 176, in loads
    item + "'. Try quoting the key name.")
toml.TomlDecodeError: Found invalid character in key name: '['. Try quoting the key name.

是user文件只填写账号密码不能运行嘛?
![image](https://user-images.githubusercontent.com/20513450/54073089-154b8100-42be-11e9-9b02-8137933d3015.png)

**Comment by yjqiang** [comment]
https://github.com/yjqiang/bili2.0/issues/39
