### ISSUE TITLE
api未知输出格式

### ISSUE THREAD

**Issue by Kjcdkcnjji** [yjqiang/bili2.0#8]
![e](https://user-images.githubusercontent.com/41225012/44096717-84d11718-a00e-11e8-960e-16e19230d7f1.png)

**Comment by yjqiang** [comment]
未知输出情况，b站sb

**Comment by Love4Taylor** [comment]
类似的返回
```
Task exception was never retrieved
future: <Task finished coro=<Notifier.__exec_one_step() done, defined at /home/love4taylor/scripts/bili2.0/notifier.py:42> exception=TypeError('list indices must be integers or slices, not str')>
Traceback (most recent call last):
  File "/home/love4taylor/scripts/bili2.0/notifier.py", line 46, in __exec_one_step    results = await self.notify(id, func, *args)
  File "/home/love4taylor/scripts/bili2.0/notifier.py", line 20, in notify
    result = await self.users[id].accept(func, *args)
  File "/home/love4taylor/scripts/bili2.0/user.py", line 113, in accept
    return await func(self, *args)
  File "/home/love4taylor/scripts/bili2.0/tasks/live_daily_job.py", line 276, in send_gift
    await SendGiftTask.send_medal_gift(user)
  File "/home/love4taylor/scripts/bili2.0/tasks/live_daily_job.py", line 248, in send_medal_gift
    await SendGiftTask.fill_intimacy(user, send_giftbags, medals)
  File "/home/love4taylor/scripts/bili2.0/tasks/live_daily_job.py", line 267, in fill_intimacy
    await UtilsTask.send_gift(user, room_id, num_sent, bag_id, gift_id)
  File "/home/love4taylor/scripts/bili2.0/tasks/utils.py", line 80, in send_gift
    ruid = json_rsp['data']['uid']
TypeError: list indices must be integers or slices, not str
```

**Comment by yjqiang** [comment]
算了，我加个debug吧。这玩意肯定是返回频繁啦之类的

**Comment by yjqiang** [comment]
@Kjcdkcnjji @Love4Taylor 刚刚更新了，加了一个debug信息，你们如果发现文件夹内有log文件，就发给我。

**Comment by yjqiang** [comment]
https://github.com/yjqiang/bili2.0/commit/2119387dcc00abc5fec9deb45910154362cb1d01 加入了json rsp pattern匹配通过黑白名单协同控制数据处理
