### ISSUE TITLE
出现了这样子的错误，是怎么回事？我的步骤应该没有错误。

### ISSUE THREAD

**Issue by yushengleiming** [yjqiang/bili2.0#81]
Traceback (most recent call last):
  File "run.py", line 31, in <module>
    from dyn.monitor_dyn_raffle import DynRaffleMonitor
  File "C:\Users\Administrator\Desktop\bili2.0-master\dyn\monitor_dyn_raffle.py", line 5, in <module>
    from .bili_data_types import DynRaffleStatus, DynRaffleResults
  File "C:\Users\Administrator\Desktop\bili2.0-master\dyn\bili_data_types.py", line 60, in <module>
    @attr.s(frozen=True)
  File "C:\Users\Administrator\Desktop\bili2.0-master\dyn\bili_data_types.py", line 72, in DynRaffleResults
    validator=attr.validators.deep_iterable(
AttributeError: module 'attr.validators' has no attribute 'deep_iterable'

**Comment by yjqiang** [comment]
https://github.com/yjqiang/bili2.0/issues/68
