### ISSUE TITLE
小白遇到了问题（重装了python 然后解决  ）

### ISSUE THREAD

**Issue by k471559444** [yjqiang/bili2.0#83]
新的版本会有这个提示请问该怎么处理啊自己弄了那两个toml文件了呀也写了

Traceback (most recent call last):
  File "run.py", line 31, in <module>
    from dyn.monitor_dyn_raffle import DynRaffleMonitor
  File "D:\bilibili\bili2.0-master\dyn\monitor_dyn_raffle.py", line 6, in <module>
    from .bili_data_types import DynRaffleStatus, DynRaffleResults
  File "D:\bilibili\bili2.0-master\dyn\bili_data_types.py", line 60, in <module>
    @attr.s(frozen=True)
  File "D:\bilibili\bili2.0-master\dyn\bili_data_types.py", line 72, in DynRaffleResults
    validator=attr.validators.deep_iterable(
AttributeError: module 'attr.validators' has no attribute 'deep_iterable'

**Comment by yjqiang** [comment]
https://github.com/yjqiang/bili2.0/issues/68
请务必善用搜索引擎
