### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by Cartagra** [yjqiang/bili2.0#97]
[root@iz4byri71e6ptaz ~]# python36 bili2.0-master/run.py
Traceback (most recent call last):
  File "bili2.0-master/run.py", line 9, in <module>
    from bili_console import Biliconsole
  File "/root/bili2.0-master/bili_console.py", line 8, in <module>
    from tasks.custom import SendLatiaoTask, BuyLatiaoTask
  File "/root/bili2.0-master/tasks/custom.py", line 2, in <module>
    from tasks.live_daily_job import SendGiftTask
  File "/root/bili2.0-master/tasks/live_daily_job.py", line 4, in <module>
    from reqs.live_daily_job import (
  File "/root/bili2.0-master/reqs/live_daily_job.py", line 3, in <module>
    from json_rsp_ctrl import Ctrl, BaseCtrl, CtrlElem, Equal, In, JsonRspType
  File "/root/bili2.0-master/json_rsp_ctrl.py", line 31, in <module>
    @attr.s(slots=True, frozen=True)
  File "/root/bili2.0-master/json_rsp_ctrl.py", line 33, in DeepIn
    keys = attr.ib(validator=attr.validators.deep_iterable(
AttributeError: module 'attr.validators' has no attribute 'deep_iterable'

**Comment by yjqiang** [comment]
更新attrs
